
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'burstbank'
version: '1.0.0'
config-version: 2

profile: 'burstbank'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

require-dbt-version: [">=1.9.0", "<2.0.0"]

models:
  burstbank:
    +database: lakehouse
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
