version: 2

sources:
  - name: burstbank
    database: sample
    schema: burstbank
    tables:
      - name: account
      - name: auto_loan_payment
      - name: credit_card_payment
      - name: customer
      - name: customer_profile
      - name: employee
      - name: mortgage_payment
      - name: product_profile
      - name: state_census
